### ISSUE TITLE
Pods Malfunction

### ISSUE THREAD

**Issue by viniciusvieir** [fpg1503/sinesp-swift#4]
I'm getting the following error message when I try to install the pod through Cocoapods:

> [!] Unable to satisfy the following requirements:
> 
> - `AEXML` required by `Podfile`
> - `AEXML (= 4.1.0)` required by `Podfile.lock`
> - `AEXML (~> 3.0)` required by `sinesp (0.1.0)`

Is it possible to be fixed, since the AEXML 3.0 version does not work with the current version of swift?

Thanks!

**Comment by fpg1503** [comment]
Sorry for any inconvenience it may have caused, can you give it a try now? (I've published v1.0.0)

**Comment by fpg1503** [comment]
The request format has changed, I'm working on fixing it

**Comment by fpg1503** [comment]
Done 😄
